spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8084/
          predicates:
            - Path=/clients/**
        - id: r2
          uri: http://localhost:8085/
          predicates:
            - Path=/produits/**
